import "./check-runtime.mjs";
import { run } from "./lib/git.mjs";

// Database fixtures are generated by the separate Postgres test lane.
const env = { ...process.env };
delete env.USAGEKIT_POSTGRES_TEST_URL;
run(process.execPath, ["node_modules/vitest/vitest.mjs", ...process.argv.slice(2)], {
  env,
  stdio: "inherit",
});
